#!/bin/csh -f 
#
# Usage:  maketexdocs <srcdir>
#
setenv SRC $argv[1]
foreach table ( elementstable simpletypestable grouptypestable ades )
${SRC}/Python/ades/applyxslt ${SRC}/xml/adesmaster.xml ${SRC}/xslt/latex//doc{$table}.xslt > {$table}.tex
end
