#!/bin/csh -f

#
# apply xlst to adesmaster file to make xsd files in four formats
#

../Python/ades/applyxslt ../xml/adesmaster.xml ../xslt/xsd/generalxsd.xslt > general.xsd
#../Python/bin/applyxslt ../xml/adesmaster.xml ../xslt/xsd/generalhumanxsd.xslt > generalhuman.xsd
../Python/ades/applyxslt ../xml/adesmaster.xml ../xslt/xsd/submitxsd.xslt > submit.xsd
#../Python/bin/applyxslt ../xml/adesmaster.xml ../xslt/xsd/submithumanxsd.xslt > submithuman.xsd
